FROM registry.access.redhat.com/ubi9/ubi:latest

# NOTE: keep packages in sync with tmt/main.fmf
RUN dnf -y install \
    make \
    python3-devel \
    python3-pyyaml \
    python3-setuptools \
    rpmdevtools \
    pyproject-rpm-macros \
    python3-wheel \
&& dnf clean all
